on: [ push, pull_request ]
name: Linux
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.23.x ]
        os: [ ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: mod
        run: go mod download
      - name: Test
        run: go test -count=1 ./...
